export const categories = [
    "Adoption",
    "Children",
    "Elder Care",
    "Fatherhood",
    "Motherhood",
    "Parenting",
    "Pregnancy",
    "Seniors",
    "Anxiety",
    "Counseling",
    "Grief",
    "Life Lessons",
    "Self-awareness",
    "Stress",
    "Therapy",
    "Trauma",
    "Mental Health",
    "Business",
    "Entrepreneurship",
    "Freelancing",
    "Small Business",
    "Startups",
    "Venture Capital",
    "Health",
    "Aging",
    "Coronavirus",
    "Covid-19",
    "Death And Dying",
    "Disease",
    "Fitness",
    "Mens Health",
    "Nutrition",
    "Sleep",
    "Trans Healthcare",
    "Vaccines",
    "Weight Loss",
    "Womens Health",
    "Productivity",
    "Career Advice",
    "Coaching",
    "Goal Setting",
    "Morning Routines",
    "Pomodoro Technique",
    "Time Management",
    "Work Life Balance",
    "Marketing",
    "Advertising",
    "Branding",
    "Content Marketing",
    "Content Strategy",
    "Digital Marketing",
    "SEO",
    "Social Media Marketing",
    "Storytelling For Business",
    "Mindfulness",
    "Guided Meditation",
    "Journaling",
    "Meditation",
    "Transcendental Meditation",
    "Yoga",
    "Leadership",
    "Employee Engagement",
    "Leadership Coaching",
    "Leadership Development",
    "Management",
    "Meetings",
    "Org Charts",
    "Thought Leadership",
    "Relationships",
    "Dating",
    "Divorce",
    "Friendship",
    "Love",
    "Marriage",
    "Polyamory",
    "Sexuality",
    "BDSM",
    "Erotica",
    "Kink",
    "Sex",
    "Sexual Health",
    "Home",
    "Architecture",
    "Home Improvement",
    "Homeownership",
    "Interior Design",
    "Rental Property",
    "Vacation Rental",
    "Food",
    "Baking",
    "Coffee",
    "Cooking",
    "Foodies",
    "Restaurants",
    "Tea",
    "Pets",
    "Cats",
    "Dog Training",
    "Dogs",
    "Hamsters",
    "Horses",
    "Pet Care",
    "Remote Work",
    "Company Retreats",
    "Digital Nomads",
    "Distributed Teams",
    "Future Of Work",
    "Work From Home",
    "Technology",
    "Artificial Intelligence",
    "ChatGPT",
    "Conversational AI",
    "Deep Learning",
    "Large Language Models",
    "Machine Learning",
    "NLP",
    "Voice Assistant",
    "Software Development",
    "Programming",
    "Android Development",
    "Coding",
    "Flutter",
    "Frontend Engineering",
    "iOS Development",
    "Mobile Development",
    "Software Engineering",
    "Web Development",
    "Media",
    "Writing",
    "30 Day Challenge",
    "Book Reviews",
    "Books",
    "Creative Nonfiction",
    "Diary",
    "Fiction",
    "Haiku",
    "Hello World",
    "Memoir",
    "Nonfiction",
    "Personal Essay",
    "Poetry",
    "Screenwriting",
    "Short Stories",
    "This Happened To Me",
    "Writing Prompts",
    "Writing Tips",
    "Blockchain",
    "Bitcoin",
    "Cryptocurrency",
    "Decentralized Finance",
    "Ethereum",
    "Nft",
    "Web3",
    "Programming Languages",
    "Angular",
    "CSS",
    "HTML",
    "Java",
    "JavaScript",
    "Nodejs",
    "Python",
    "React",
    "Ruby",
    "Typescript",
    "Data Science",
    "Analytics",
    "Data Engineering",
    "Data Visualization",
    "Database Design",
    "Sql",
    "NoSql",
    "Dev Ops",
    "AWS",
    "Databricks",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Art",
    "Comics",
    "Contemporary Art",
    "Drawing",
    "Fine Art",
    "Generative Art",
    "Illustration",
    "Painting",
    "Portraits",
    "Street Art",
    "Gaming",
    "Game Design",
    "Game Development",
    "Indie Game",
    "Metaverse",
    "Nintendo",
    "PlayStation",
    "Videogames",
    "Virtual Reality",
    "Xbox",
    "Gadgets",
    "eBook",
    "Internet of Things",
    "iPad",
    "Smart Home",
    "Smartphones",
    "Wearables",
    "Makers",
    "3D Printing",
    "Arduino",
    "DIY",
    "Raspberry Pi",
    "Robotics",
    "Security",
    "Cybersecurity",
    "Data Security",
    "Encryption",
    "Infosec",
    "Passwords",
    "Privacy",
    "Tech Companies",
    "Amazon",
    "Apple",
    "Google",
    "Mastodon",
    "Medium",
    "Meta",
    "Microsoft",
    "Tiktok",
    "Twitter",
    "Design",
    "Accessibility",
    "Design Systems",
    "Design Thinking",
    "Graphic Design",
    "Icon Design",
    "Inclusive Design",
    "Product Design",
    "Typography",
    "UX Design",
    "UX Research",
    "Product Management",
    "Agile",
    "Innovation",
    "Kanban",
    "Lean Startup",
    "MVP",
    "Product",
    "Strategy",
    "Operating Systems",
    "Android",
    "iOS",
    "Linux",
    "Macos",
    "Windows",
    "Humor",
    "Comedy",
    "Jokes",
    "Parody",
    "Satire",
    "Stand Up Comedy",
    "Movies",
    "Cinema",
    "Film",
    "Filmmaking",
    "Movie Reviews",
    "Oscars",
    "Music",
    "Hip Hop",
    "Indie",
    "Metal",
    "Pop",
    "Rap",
    "Rock",
    "Blues",
    "Trap",
    "News",
    "Data Journalism",
    "Fake News",
    "Journalism",
    "Misinformation",
    "True Crime",
    "Photography",
    "Cameras",
    "Photography Tips",
    "Photojournalism",
    "Photos",
    "Street Photography",
    "Podcasts",
    "Podcast Equipment",
    "Podcast Recommendations",
    "Podcasting",
    "Podcasting Tips",
    "Radio",
    "Television",
    "Hbo Max",
    "Hulu",
    "Netflix",
    "Reality TV",
    "Tv Reviews",
    "Society",
    "Economics",
    "Basic Income",
    "Debt",
    "Economy",
    "Inflation",
    "Stock Market",
    "Philosophy",
    "Atheism",
    "Epistemology",
    "Ethics",
    "Existentialism",
    "Metaphysics",
    "Morality",
    "Philosophy Of Mind",
    "Stoicism",
    "Abu Dhabi",
    "Amsterdam",
    "Athens",
    "Bangkok",
    "Barcelona",
    "Berlin",
    "Boston",
    "Buenos Aires",
    "Chicago",
    "Copenhagen",
    "Delhi",
    "Dubai",
    "Dublin",
    "Edinburgh",
    "Glasgow",
    "Hong Kong",
    "Istanbul",
    "Lisbon",
    "London",
    "Los Angeles",
    "Madrid",
    "Melbourne",
    "Mexico City",
    "Miami",
    "Montreal",
    "New York City",
    "Paris",
    "Prague",
    "Rio De Janeiro",
    "Rome",
    "San Francisco",
    "Sydney",
    "Taipei",
    "Tel Aviv",
    "Tokyo",
    "Toronto",
    "Vancouver",
    "Vienna",
    "Education",
    "Charter Schools",
    "Education Reform",
    "Higher Education",
    "PhD",
    "Public Schools",
    "Student Loans",
    "Study Abroad",
    "Teaching",
    "Religion",
    "Buddhism",
    "Christianity",
    "Hinduism",
    "Islam",
    "Judaism",
    "Zen",
    "Equality",
    "Disability",
    "Discrimination",
    "Diversity In Tech",
    "Feminism",
    "Inclusion",
    "LGBTQ",
    "Racism",
    "Transgender",
    "Womens Rights",
    "Spirituality",
    "Astrology",
    "Energy Healing",
    "Horoscopes",
    "Mysticism",
    "Reiki",
    "Cultural Studies",
    "Ancient History",
    "Anthropology",
    "Cultural Heritage",
    "Digital Life",
    "History",
    "Museums",
    "Sociology",
    "Tradition",
    "Fashion",
    "Clothing",
    "Fashion Design",
    "Fashion Trends",
    "Shoes",
    "Sneakers",
    "Style",
    "Beauty",
    "Beauty Tips",
    "Body Image",
    "Hair",
    "Makeup",
    "Skincare",
    "Language",
    "Arabic",
    "English Language",
    "English Learning",
    "French",
    "German",
    "Hindi",
    "Language Learning",
    "Linguistics",
    "Mandarin",
    "Portuguese",
    "Spanish",
    "Sports",
    "Baseball",
    "Basketball",
    "Football",
    "NBA",
    "NFL",
    "Premier League",
    "Soccer",
    "World Cup",
    "Finance",
    "Investing",
    "Money",
    "Philanthropy",
    "Real Estate",
    "Retirement",
    "Law",
    "Criminal Justice",
    "Law School",
    "Legaltech",
    "Social Justice",
    "Supreme Court",
    "Transportation",
    "Logistics",
    "Public Transit",
    "Self Driving Cars",
    "Trucking",
    "Urban Planning",
    "Politics",
    "Elections",
    "Government",
    "Gun Control",
    "Immigration",
    "Political Parties",
    "Race",
    "American Indian",
    "Anti Racism",
    "Asian American",
    "Black Lives Matter",
    "Indigenous People",
    "Multiracial",
    "Pacific Islander",
    "White Privilege",
    "White Supremacy",
    "Science",
    "Archaeology",
    "Astronomy",
    "Astrophysics",
    "Biotechnology",
    "Chemistry",
    "Ecology",
    "Genetics",
    "Geology",
    "Medicine",
    "Neuroscience",
    "Physics",
    "Psychology",
    "Space",
    "Mathematics",
    "Algebra",
    "Calculus",
    "Geometry",
    "Probability",
    "Statistics",
    "Drugs",
    "Addiction",
    "Cannabis",
    "Opioids",
    "Pharmaceuticals",
    "Psychedelics",
    "Gang Wars",
];